const {
  getBranch,
  getCareerMobility,
  getCompetency,
  getDiploma,
  getDevelopmentalGoals,
  getGroupLevel,
  getKeyCompetency,
  getLocation,
  getSchool,
  getSecurityClearance,
  getCategory,
  getCategorySkills,
  getSkill,
  getTalentMatrixResult,
  getTenure,
  getLookingForANewJob,
  getWillingToRelocateTo,
} = require("./get");

const optionRouter = require("./router");

module.exports = {
  getBranch,
  getCareerMobility,
  getCompetency,
  getDiploma,
  getDevelopmentalGoals,
  getGroupLevel,
  getKeyCompetency,
  getLocation,
  getSchool,
  getSecurityClearance,
  getCategory,
  getCategorySkills,
  getSkill,
  getTalentMatrixResult,
  getTenure,
  getLookingForANewJob,
  getWillingToRelocateTo,
  optionRouter,
};
