FROM node:12-alpine

ENV TZ=America/Toronto
ENV NODE_ENV=production

WORKDIR /upskill-frontend
COPY . .

RUN chown -Rh $user:$user /upskill-frontend
USER $user

RUN yarn install 
RUN yarn cache clean

CMD ["yarn", "deploy"]