version: "3"
services:
  web-ant:
    container_name: "upskill-frontend"
    build: ./services/frontend-v3
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend-v3:/upskill-frontend
      - frontend-node-modules:/upskill-backend/node_modules
    env_file:
      - ./env/web.env

  backend:
    container_name: "upskill-backend"
    build: ./services/backend
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes:
      - ./services/backend:/upskill-backend
      - backend-node-modules:/upskill-backend/node_modules
    env_file:
      - ./env/backend.env
      - .env
    networks:
      - redis-net
      - postgres-net
    depends_on:
      - redis
      - db-postgres

  db-postgres:
    container_name: "upskill-database"
    image: "postgres:12-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    hostname: db-postgres
    environment:
      POSTGRES_PASSWORD: api
      POSTGRES_USER: api
      POSTGRES_DB: testdb
    networks:
      - postgres-net
    ports:
      - "5432:5432"

  redis:
    container_name: "upskill-redis-session"
    image: "redis:6-alpine"
    command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    hostname: redis
    restart: always
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  keycloak:
    container_name: "upskill-keycloak"
    image: "jboss/keycloak"
    volumes:
      - ./keycloak:/opt/jboss/keycloak/keycloak
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/keycloak/realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"

networks:
  redis-net:
  postgres-net:

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
  backend-node-modules:
  frontend-node-modules:
