version: "3.5"
services:
  frontend:
    container_name: italent-frontend
    image: italent-frontend
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000 # port neutrino.js
      - 3031:3031 # port for webpack analyzer
    volumes:
      - ./services/frontend:/italent-frontend
      - frontend-data:/italent-frontend/node_modules
    env_file:
      - ./env/web.env
    stdin_open: true

  backend:
    container_name: italent-backend
    image: italent-backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080 # port backend API
      - 5555:5555 # port for Prisma Studio
    volumes:
      - ./services/backend:/italent-backend
      - backend-data:/italent-backend/node_modules
    env_file:
      - ./env/backend.env
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: italent-postgres
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: api
      POSTGRES_USER: api
      POSTGRES_DB: testdb

  redis:
    container_name: italent-redis
    image: redis:6-alpine
    command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    hostname: redis
    restart: always
    volumes:
      - redis-data:/data

networks:
  default:
    name: italent-network

volumes:
  postgres-data:
    name: italent-postgres-data
  redis-data:
    name: italent-redis-data
  backend-data:
    name: italent-backend-data
  frontend-data:
    name: italent-frontend-data
