version: "3"
services:
  web-ant:
    container_name: "upskill-frontend"
    build: 
      context: ./services/frontend-v3
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./services/frontend-v3:/upskill-frontend
      - frontend-node-modules:/upskill-frontend/node_modules
    env_file:
      - ./env/web.env

  backend:
    container_name: "upskill-backend"
    build: 
      context: ./services/backend
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes:
      - ./services/backend:/upskill-backend
      - backend-node-modules:/upskill-backend/node_modules
    env_file:
      - ./env/backend.env
      - .env
    depends_on:
      - redis
      - db-postgres

  db-postgres:
    container_name: "upskill-database"
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    hostname: db-postgres
    environment:
      POSTGRES_PASSWORD: api
      POSTGRES_USER: api
      POSTGRES_DB: testdb

  redis:
    container_name: "upskill-redis-session"
    image: "redis:6-alpine"
    ports:
      - "6379:6379"
    command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    hostname: redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
  backend-node-modules:
  frontend-node-modules:
