version: "3"
services:
  web-ant:
    container_name: "upskill-frontend"
    build: ./services/frontend-v3
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend-v3:/upskill-frontend
      - ./upskill-frontend/node_modules
    env_file:
      - ./env/web.env

  backend:
    container_name: "upskill-backend"
    build: ./services/backend
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes:
      - ./services/backend:/upskill-backend
      - ./upskill-backend/node_modules
    env_file:
      - ./env/backend.env

  db-postgres:
    container_name: "upskill-database"
    image: "postgres:12-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: api
      POSTGRES_USER: api
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
