FROM node:12-alpine

ENV TZ=America/Toronto
ENV NODE_ENV=production

USER $user

WORKDIR /upskill-backend
RUN npm -g config set user $user

COPY package.json ./
COPY yarn.lock ./

# RUN mkdir -p /opt/upskill-backend/.yarn-cache
# ENV YARN_CACHE_FOLDER=/opt/upskill-backend/.yarn-cache

RUN yarn install
RUN yarn cache clean

COPY . .

RUN yarn generate

EXPOSE 3000

CMD ["yarn", "deploy"]