FROM node:12-alpine

# USER node

USER $user

ENV TZ=America/Toronto
ENV NODE_ENV=production

RUN mkdir /upskill-backend
WORKDIR /upskill-backend
COPY . .

RUN yarn install
RUN yarn cache clean
RUN yarn generate

CMD ["yarn", "deploy"]
