FROM node:14.15.3-alpine3.12

ENV TZ=America/Toronto

# Set working directory
RUN mkdir /italent-backend
WORKDIR /italent-backend

# Copy app dependencies
COPY package*.json ./

# Runs install script
RUN npm install

# Copy app
COPY . .

# Runs start script
CMD npm docker:dev
