FROM node:14.15.1-alpine3.12

ENV TZ=America/Toronto

# Set working directory
RUN mkdir /italent-backend
WORKDIR /italent-backend

# Copy app dependencies
COPY package.json yarn.lock ./

# Runs install script
RUN yarn install

# Copy app
COPY . .

# Runs start script
CMD yarn docker:dev
