FROM node:14.15.3-alpine3.12

ENV TZ=America/Toronto

# Set working directory
RUN mkdir /italent-frontend
WORKDIR /italent-frontend

# Copy app dependencies
COPY package.json yarn.lock ./

# Runs install script
RUN yarn install

# Copy app
COPY . .

# Runs start script
CMD yarn dev
