name: backend-tests

on:
  pull_request:
    branches: [development]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./services/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: c-hive/gha-yarn-cache@v1

      - name: Installing Yarn dependencies
        run: yarn install

      - name: Run generate
        run: yarn generate
      - name: Run tests
        run: yarn test
