name: Linter

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./services/frontend-v3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run linter
        run: npx eslint ./src --ext .js,.jsx

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./services/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run linter
        run: npx eslint ./src --ext .js,.jsx

  i18n:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./services/frontend-v3/src/i18n

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Installing Yarn dependencies
        run: npm init -y && yarn add lodash

      - name: Run i18n linter
        run: node check
